In [55]:
import pandas as pd
from IPython.display import display

In [56]:
# Series => Series are 1 dim array like Object which is similar to Column in an table
data_1 = [1, 2, 3, 4, 5]
pd.Series(data=data_1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [57]:
# Creating a Series from dictionary element
# Since dictionary has key and value => Key will be map to index (either number or label if string type) and value will be the actual value of a Series
my_dic = dict({101: 1, 102: 2, 103: 3, 104: 4, 105: 5})
print("Creating Series from dictionary : \n", pd.Series(my_dic))

Creating Series from dictionary :
 101    1
102    2
103    3
104    4
105    5
dtype: int64

In [58]:
my_dict = {
    "Name": ["Rahul", "Pursotam", "undertaker"],
    "Age": [20, 21, 22],
    "City": ["Delhi", "Kolkata", "Chennai"],
}
# creating df from dictionary
df = pd.DataFrame(
    my_dict, index=[1, 2, 3]
)  # here index=[] will be new label for the rows
display(df)

         Name  Age     City
1       Rahul   20    Delhi
2    Pursotam   21  Kolkata
3  undertaker   22  Chennai

In [59]:
# Data manipulation using pandas

# Adding new column i,e salary to this df
df["Salary"] = df["Age"] * 10000
display(df)
#  droping the salary column
df.drop(
    "Salary", axis=1, inplace=True
)  # inplace will make permanent change in df instead of returning new df with droped column
print("dataframe after dropping salary column")
display(df)

         Name  Age     City  Salary
1       Rahul   20    Delhi  200000
2    Pursotam   21  Kolkata  210000
3  undertaker   22  Chennai  220000

dataframe after dropping salary column

         Name  Age     City
1       Rahul   20    Delhi
2    Pursotam   21  Kolkata
3  undertaker   22  Chennai

In [60]:
# get the Statistical summary of the dataframe
df.describe()

        Age
count   3.0
mean   21.0
std     1.0
min    20.0
25%    20.5
50%    21.0
75%    21.5
max    22.0

#### Some basic data manipulation in pandas

In [61]:
# DataFrame => They are collection of Pandas Series. So they represent both rows and columns of a table
# read the csv file
sales_df = pd.read_csv("sales_data.csv")
# print the first 5 entry of the dataframe
display("The first 5 entry of the sales data :", sales_df.head(5))

'The first 5 entry of the sales data :'

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [62]:
# Accessing data from dataframe
sales_df["Product Category"].head(4)

0        Electronics
1    Home Appliances
2           Clothing
3              Books
Name: Product Category, dtype: str

In [63]:
# indexing in dataframe
# loc = it uses label based indexing i.e based on label name it can access the data .loc[row,col]
print(
    sales_df.loc[0, "Product Category"]
)  # here we use 0 as row because by default the lable for row in df is 0,1,2 and so on
# iloc is used for accessing using index position like 0,1,2,3 and so on
print(sales_df.iloc[0, 2])  # here the data is access based on pure index value

Electronics
Electronics