### Some important data manipulation used in pandas

In [18]:
import pandas as pd
from IPython.display import display

In [19]:
# read the data.csv file
df = pd.read_csv("data.csv")
# print the firt 5 entry of the dataframe
display(df.head(5))

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [20]:
# statistical analysis of the dataframe
display(df.describe())

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [21]:
# print how many null or empty values are present in the dataframe for the respective column
df["Sales"].isnull().sum()
# ? check if any column is there that has any missing values
display(df.isnull().any())
# We can see

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [23]:
# Handling Missing Values

# drop all the rows that has any missing values in any of its columns
# df.dropna(inplace=True)

# filling the null values in a column with mean of that column
df["Value"] = df["Value"].fillna(df["Value"].mean())
df["Sales"] = df["Sales"].fillna(df["Sales"].mean())
df.isnull().sum()

Date        0
Category    0
Value       0
Product     0
Sales       0
Region      0
dtype: int64

In [27]:
# Rename old column name with new column name
# First Print all the column name
print(df.columns)
# rename Sales to TotalSales
df.rename(columns={"Sales": "TotalSales"}, inplace=True)
# Print after renaming column
print(df.columns)

Index(['Date', 'Category', 'Value', 'Product', 'Sales', 'Region'], dtype='str')
Index(['Date', 'Category', 'Value', 'Product', 'TotalSales', 'Region'], dtype='str')

In [33]:
# * Applying function to change or add new column data
print(df["Value"].head())
df["Value"] = df["Value"].apply(lambda x: x * 2)
print("=======After applying lambda function ======= : \n", df["Value"].head())

0    224.0
1    312.0
2    256.0
3     64.0
4    208.0
Name: Value, dtype: float64
=======After applying lambda function ======= :
 0    448.0
1    624.0
2    512.0
3    128.0
4    416.0
Name: Value, dtype: float64

In [ ]:
# * Data Aggreagting and Grouping
# Find the total sum of values for each product
display(df.groupby("Product")["Value"].sum())
# we can group by based on 2 or many categorical columns
display(df.groupby(["Product", "Region"])["Value"].sum())
df.head()

Product
Product1    12007.829787
Product2    12672.000000
Product3    16715.914894
Name: Value, dtype: float64

Product   Region
Product1  East      4672.000000
          North      971.914894
          South     1600.000000
          West      4763.914894
Product2  East       896.000000
          North     2032.000000
          South     2896.000000
          West      6848.000000
Product3  East      3232.000000
          North     4075.914894
          South     3440.000000
          West      5968.000000
Name: Value, dtype: float64

         Date Category  Value   Product  TotalSales Region
0  2023-01-01        A  448.0  Product1       754.0   East
1  2023-01-02        B  624.0  Product3       110.0  North
2  2023-01-03        C  512.0  Product2       398.0   East
3  2023-01-04        B  128.0  Product1       522.0   East
4  2023-01-05        B  416.0  Product3       869.0  North

In [52]:
# Merging two dataframe rowise and column wise
df1 = pd.DataFrame({"col1": [1, 2, 3], "col2": [4, 5, 6]})
df2 = pd.DataFrame({"col1": [1, 2, 4], "col3": [42, 53, 64]})
# Merging Inner join
print(pd.merge(df1, df2, on="col1", how="inner"))
print("============================>")
# Merging Outer Join
print(pd.merge(df1, df2, on="col1", how="outer"))
print("============================>")
# Merging left Join
print(pd.merge(df1, df2, on="col1", how="left"))

   col1  col2  col3
0     1     4    42
1     2     5    53
============================>
   col1  col2  col3
0     1   4.0  42.0
1     2   5.0  53.0
2     3   6.0   NaN
3     4   NaN  64.0
============================>
   col1  col2  col3
0     1     4  42.0
1     2     5  53.0
2     3     6   NaN